name: Generator
on: [push, pull_request]
jobs:
  ngxadmin:
    name: npm-test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.20.0'
      - run: npm ci
      - run: npm run test
